/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Citlali Vazquez
 */
public class Prod2_panel extends javax.swing.JPanel {

    /**
     * Creates new form Prod2_panel
     */
    public Prod2_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(103, 148, 107));
        setPreferredSize(new java.awt.Dimension(170, 130));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/peyoodoll (2).jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(170, 130));
        add(jLabel1, new java.awt.GridBagConstraints());

        jButton2.setBackground(new java.awt.Color(175, 247, 186));
        jButton2.setText("Ver");
        add(jButton2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
